"""create votes table

Revision ID: 5c2df512c47f
Revises: 1147f32b49df
Create Date: 2025-09-07 00:05:31.128348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c2df512c47f'
down_revision: Union[str, Sequence[str], None] = '1147f32b49df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('post_id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('post_id', 'user_id')
                    )
    pass


def downgrade() -> None:
    op.drop_table('votes')
    pass
